# Generated by Django 5.1.7 on 2025-03-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('phone', models.CharField(max_length=127)),
                ('message', models.TextField()),
            ],
        ),
    ]
